ghost-blog:
  image: "ghost:latest"
  ports:
    - "2368:2368"
  volumes:
    - '.:/var/lib/ghost'
sass:
  build: "https://github.com/trflagg/sass-docker.git"
  volumes:
    - '.:/src'
  command:  --watch /src/sass:/src/themes
